/**
 * Shared user-facing strings for all report outputs (HTML, PDF, Markdown).
 * Edit here once; all exporters stay in sync automatically.
 *
 * @module export/strings
 */

export const APP_NAME = 'Social Media Post Accessibility Checker';

export const SITE_URL = 'https://github.com/timdixon82/Social-Media-Accessibility-Checker-Extension';

export const THRESHOLDS_FOOTER =
  'Contrast thresholds — AA: 4.5:1 normal / 3:1 large text · '
  + 'AAA: 7:1 normal / 4.5:1 large text. '
  + 'Large text = ≥24 px OCR box height. '
  + 'Detected via PaddleOCR PP-OCRv4.';

export const DISCLAIMER_TEXT =
  'This report is generated by automated tools and may not identify all accessibility issues. '
  + 'Results should be verified by manual testing with assistive technology.';
